const SKILLS = [
  {
    id: 'prestige_start',
    tier: 1,
    name: '프레스티지 시작',
    icon: '🏠',
    cost: 10,
    effect: { type: 'none' },
    autoUnlock: true,
    description: '모든 프레스티지 여정의 시작점입니다. 첫 번째 프레스티지를 완료하면 자동으로 해금됩니다.'
  },
  {
    id: 'click_boost_1',
    tier: 2,
    name: '클릭 강화 I',
    icon: '👆',
    cost: 15,
    requires: ['prestige_start'],
    effect: { type: 'click_percent', value: 10 },
    description: '클릭으로 얻는 모든 쿠키가 영구적으로 10% 증가합니다.'
  },
  {
    id: 'cps_boost_1',
    tier: 2,
    name: '생산력 강화 I',
    icon: '📈',
    cost: 15,
    requires: ['prestige_start'],
    effect: { type: 'cps_percent', value: 10 },
    description: '초당 자동 생산량(CPS)이 영구적으로 10% 증가합니다.'
  },
  {
    id: 'cost_discount_1',
    tier: 2,
    name: '비용 할인 I',
    icon: '💰',
    cost: 15,
    requires: ['prestige_start'],
    effect: { type: 'cost_discount', value: 5 },
    description: '모든 업그레이드의 구매 비용이 5% 감소합니다.'
  },
  {
    id: 'critical_click',
    tier: 3,
    name: '크리티컬 클릭',
    icon: '💥',
    cost: 25,
    requires: ['click_boost_1', 'cps_boost_1'],
    minRequired: 2,
    effect: { type: 'critical', chance: 5, multiplier: 3 },
    description: '클릭 시 5% 확률로 크리티컬이 발동하여 3배의 데미지를 입힙니다.'
  },
  {
    id: 'cookie_interest',
    tier: 3,
    name: '쿠키 이자',
    icon: '🏦',
    cost: 25,
    requires: ['cps_boost_1', 'cost_discount_1'],
    minRequired: 2,
    effect: { type: 'interest', rate: 0.1 },
    description: '현재 보유한 쿠키의 0.1%를 매초 추가로 획득합니다.'
  },
  {
    id: 'auto_click',
    tier: 3,
    name: '자동 클릭',
    icon: '🖱️',
    cost: 25,
    requires: ['click_boost_1', 'cost_discount_1'],
    minRequired: 2,
    effect: { type: 'auto_click', rate: 1 },
    description: '매초 1회 자동으로 클릭을 수행합니다.'
  },
  {
    id: 'lucky_blessing',
    tier: 4,
    name: '행운의 축복',
    icon: '🍀',
    cost: 30,
    requires: ['critical_click', 'cookie_interest'],
    minRequired: 2,
    effect: { type: 'luck_bonus', value: 10 },
    description: '모든 확률 기반 효과의 발동 확률이 10%포인트 증가합니다.'
  },
  {
    id: 'reinforce_bonus',
    tier: 4,
    name: '강화 보너스',
    icon: '⏱️',
    cost: 30,
    requires: ['critical_click', 'auto_click'],
    minRequired: 2,
    effect: { type: 'reinforce_bonus', value: 30 },
    description: '강화의 효과가 30% 증가합니다.'
  },
  {
    id: 'start_bonus',
    tier: 4,
    name: '시작 보너스',
    icon: '🎁',
    cost: 30,
    requires: ['cookie_interest', 'auto_click'],
    minRequired: 2,
    effect: { type: 'start_bonus', cookies: 1000 },
    description: '프레스티지 후 처음 시작할 때 무료로 1,000 쿠키를 받습니다.'
  },
  {
    id: 'special_reinforce_discount',
    tier: 4,
    name: '특별 강화 할인',
    icon: '💎',
    cost: 30,
    requires: ['cookie_interest', 'critical_click'],
    minRequired: 2,
    effect: { type: 'special_reinforce_discount', value: 20 },
    description: '특별 강화의 비용이 20% 감소합니다.'
  },
  {
    id: 'burning_click',
    tier: 5,
    name: '버닝 클릭',
    icon: '🔥',
    cost: 40,
    requires: ['lucky_blessing', 'reinforce_bonus', 'start_bonus'],
    minRequired: 3,
    effect: { type: 'burning_click', stackBonus: 5, maxStack: 10 },
    description: '연속으로 클릭할 때마다 데미지가 5%씩 증가합니다. 최대 10회 중첩.'
  },
  {
    id: 'lightning',
    tier: 5,
    name: '번개의 일격',
    icon: '⚡',
    cost: 40,
    requires: ['lucky_blessing', 'special_reinforce_discount', 'start_bonus'],
    minRequired: 3,
    effect: { type: 'lightning', chance: 1, multiplier: 10 },
    description: '클릭 시 1% 확률로 번개가 떨어져 획득 쿠키가 10배가 됩니다.'
  },
  {
    id: 'star_guard',
    tier: 5,
    name: '별의 가호',
    icon: '🌟',
    cost: 40,
    requires: ['reinforce_bonus', 'special_reinforce_discount', 'start_bonus'],
    minRequired: 3,
    effect: { type: 'all_bonus', value: 10 },
    description: '모든 효과에 10% 보너스가 추가됩니다.'
  },
  {
    id: 'reset_bonus',
    tier: 6,
    name: '리셋 보너스',
    icon: '🌀',
    cost: 50,
    requires: ['burning_click', 'lightning'],
    minRequired: 2,
    effect: { type: 'star_gain_multiplier', value: 50 },
    description: '프레스티지 시 얻는 ⭐가 50% 증가합니다.'
  },
  {
    id: 'double_chance',
    tier: 6,
    name: '더블 찬스',
    icon: '💫',
    cost: 50,
    requires: ['lightning', 'star_guard'],
    minRequired: 2,
    effect: { type: 'double_chance', chance: 3, multiplier: 2 },
    description: '모든 쿠키 획득이 3% 확률로 2배가 됩니다.'
  },
  {
    id: 'carnival',
    tier: 6,
    name: '카니발',
    icon: '🎪',
    cost: 50,
    requires: ['burning_click', 'star_guard'],
    minRequired: 2,
    effect: { type: 'random_multiplier', min: 1, max: 5 },
    description: '매 클릭마다 1~5배의 랜덤 배율이 적용됩니다.'
  },
  {
    id: 'precise_hit',
    tier: 7,
    name: '정확한 타격',
    icon: '🎯',
    cost: 60,
    requires: ['reset_bonus', 'double_chance', 'carnival'],
    minRequired: 2,
    effect: { type: 'critical_multiplier_bonus', value: 50 },
    description: '크리티컬 데미지가 50% 증가합니다.'
  },
  {
    id: 'jackpot',
    tier: 7,
    name: '잭팟',
    icon: '🎰',
    cost: 60,
    requires: ['reset_bonus', 'double_chance', 'carnival'],
    minRequired: 2,
    effect: { type: 'jackpot', chance: 0.1, multiplier: 100 },
    description: '0.1%의 매우 낮은 확률로 100배의 쿠키를 획득합니다.'
  },
  {
    id: 'moon_blessing',
    tier: 7,
    name: '달빛 축복',
    icon: '🌙',
    cost: 60,
    requires: ['reset_bonus', 'double_chance', 'carnival'],
    minRequired: 2,
    effect: { type: 'time_bonus', timeRange: 'night', value: 20 },
    description: '밤 시간대(오후 10시~오전 6시)에 모든 효과가 20% 증가합니다.'
  },
  {
    id: 'sun_power',
    tier: 7,
    name: '태양의 힘',
    icon: '☀️',
    cost: 60,
    requires: ['reset_bonus', 'double_chance', 'carnival'],
    minRequired: 2,
    effect: { type: 'time_bonus', timeRange: 'day', value: 15 },
    description: '낮 시간대(오전 6시~오후 10시)에 모든 효과가 15% 증가합니다.'
  },
  {
    id: 'fate_dice',
    tier: 8,
    name: '운명의 주사위',
    icon: '🎲',
    cost: 70,
    requires: ['precise_hit', 'jackpot', 'moon_blessing', 'sun_power'],
    minRequired: 2,
    effect: { type: 'random_multiplier', min: 1, max: 6 },
    description: '매 클릭마다 1~6의 랜덤 배율이 적용됩니다.'
  },
  {
    id: 'grand_circus',
    tier: 8,
    name: '그랜드 서커스',
    icon: '🎪',
    cost: 70,
    requires: ['precise_hit', 'jackpot', 'moon_blessing', 'sun_power'],
    minRequired: 2,
    effect: { type: 'burning_upgrade', maxStack: 20, stackBonus: 7 },
    description: '버닝 클릭의 최대 중첩이 20회로 증가하고, 중첩당 보너스가 7%로 상승합니다.'
  },
  {
    id: 'change_mask',
    tier: 8,
    name: '변화의 가면',
    icon: '🎭',
    cost: 70,
    requires: ['precise_hit', 'jackpot', 'moon_blessing', 'sun_power'],
    minRequired: 2,
    effect: { type: 'random_skill_copy', chance: 10 },
    description: '각 클릭마다 10% 확률로 다른 랜덤 스킬의 효과를 1회 복사합니다.'
  },
  {
    id: 'super_booster',
    tier: 9,
    name: '슈퍼 부스터',
    icon: '🚀',
    cost: 80,
    requires: ['fate_dice', 'grand_circus', 'change_mask'],
    minRequired: 2,
    effect: { type: 'active_boost', duration: 30, bonus: 100, cooldown: 300 },
    description: '30초간 모든 효과가 100% 증가합니다. 쿨타임 5분.'
  },
  {
    id: 'ufo_abduct',
    tier: 9,
    name: 'UFO 납치',
    icon: '🛸',
    cost: 80,
    requires: ['fate_dice', 'grand_circus', 'change_mask'],
    minRequired: 2,
    effect: { type: 'bonus_chance', chance: 5, bonus: 50 },
    description: '각 클릭마다 5% 확률로 추가 쿠키 50%를 납치해옵니다.'
  },
  {
    id: 'cps_satellite',
    tier: 9,
    name: 'CPS 위성',
    icon: '🛰️',
    cost: 80,
    requires: ['fate_dice', 'grand_circus', 'change_mask'],
    minRequired: 2,
    effect: { type: 'cps_percent', value: 25 },
    description: 'CPS가 25% 증가합니다.'
  },
  {
    id: 'galaxy_power',
    tier: 9,
    name: '은하력',
    icon: '🌌',
    cost: 80,
    requires: ['fate_dice', 'grand_circus', 'change_mask'],
    minRequired: 2,
    effect: { type: 'building_cps_bonus', perBuilding: 5, maxBuildings: 10 },
    description: '모든 생산 건물이 각각 CPS에 +5% 보너스를 부여합니다. 최대 +50%.'
  },
  {
    id: 'star_grade_1',
    tier: 10,
    name: '1등급 별',
    icon: '⭐',
    cost: 100,
    requires: ['super_booster', 'ufo_abduct', 'cps_satellite', 'galaxy_power'],
    minRequired: 2,
    effect: { type: 'all_bonus', value: 5 },
    description: '모든 효과에 5% 보너스를 부여합니다.'
  },
  {
    id: 'star_grade_2',
    tier: 10,
    name: '2등급 별',
    icon: '🌟',
    cost: 100,
    requires: ['super_booster', 'ufo_abduct', 'cps_satellite', 'galaxy_power'],
    minRequired: 2,
    effect: { type: 'all_bonus', value: 10 },
    description: '모든 효과에 10% 보너스를 부여합니다.'
  },
  {
    id: 'star_shine',
    tier: 10,
    name: '별의 반짝임',
    icon: '✨',
    cost: 100,
    requires: ['super_booster', 'ufo_abduct', 'cps_satellite', 'galaxy_power'],
    minRequired: 2,
    effect: { type: 'bonus_chance', chance: 10, bonus: 50 },
    description: '각 클릭마다 10% 확률로 별이 반짝여 추가 +50% 보너스를 얻습니다.'
  },
  {
    id: 'prediction_orb',
    tier: 11,
    name: '예언의 수정구슬',
    icon: '🔮',
    cost: 120,
    requires: ['star_grade_1', 'star_grade_2', 'star_shine'],
    minRequired: 2,
    effect: { type: 'feature_unlock', feature: 'prestige_preview' },
    description: '프레스티지 전에 예상 ⭐ 획득량을 미리 볼 수 있습니다.'
  },
  {
    id: 'wisdom_necklace',
    tier: 11,
    name: '지혜의 목걸이',
    icon: '📿',
    cost: 120,
    requires: ['star_grade_1', 'star_grade_2', 'star_shine'],
    minRequired: 2,
    effect: { type: 'cps_percent', value: 20 },
    description: '영구적으로 CPS가 20% 증가합니다.'
  },
  {
    id: 'power_ring',
    tier: 11,
    name: '힘의 반지',
    icon: '💍',
    cost: 120,
    requires: ['star_grade_1', 'star_grade_2', 'star_shine'],
    minRequired: 2,
    effect: { type: 'click_percent', value: 20 },
    description: '영구적으로 클릭 데미지가 20% 증가합니다.'
  },
  {
    id: 'ruler_crown',
    tier: 11,
    name: '지배자의 왕관',
    icon: '👑',
    cost: 120,
    requires: ['star_grade_1', 'star_grade_2', 'star_shine'],
    minRequired: 2,
    effect: { type: 'all_bonus', value: 15 },
    description: '모든 효과에 15% 보너스를 받습니다.'
  },
  {
    id: 'legend_sword',
    tier: 12,
    name: '전설의 검',
    icon: '⚔️',
    cost: 140,
    requires: ['prediction_orb', 'wisdom_necklace', 'power_ring', 'ruler_crown'],
    minRequired: 2,
    effect: { type: 'click_percent', value: 40 },
    description: '클릭 데미지가 40% 증가합니다.'
  },
  {
    id: 'iron_shield',
    tier: 12,
    name: '불굴의 방패',
    icon: '🛡️',
    cost: 140,
    requires: ['prediction_orb', 'wisdom_necklace', 'power_ring', 'ruler_crown'],
    minRequired: 2,
    effect: { type: 'cost_discount', value: 10 },
    description: '모든 비용이 추가로 10% 감소합니다.'
  },
  {
    id: 'thousand_bow',
    tier: 12,
    name: '천리의 활',
    icon: '🏹',
    cost: 140,
    requires: ['prediction_orb', 'wisdom_necklace', 'power_ring', 'ruler_crown'],
    minRequired: 2,
    effect: { type: 'auto_click', rate: 2 },
    description: '자동 클릭 횟수가 +2회/초 증가합니다.'
  },
  {
    id: 'fire_dragon',
    tier: 13,
    name: '화염의 용',
    icon: '🐉',
    cost: 160,
    requires: ['legend_sword', 'iron_shield', 'thousand_bow'],
    minRequired: 2,
    effect: { type: 'all_bonus', value: 25 },
    description: '모든 효과가 25% 증가합니다.'
  },
  {
    id: 'magic_unicorn',
    tier: 13,
    name: '마법의 유니콘',
    icon: '🦄',
    cost: 160,
    requires: ['legend_sword', 'iron_shield', 'thousand_bow'],
    minRequired: 2,
    effect: { type: 'luck_bonus', value: 20 },
    description: '모든 확률 효과가 20%포인트 증가합니다.'
  },
  {
    id: 'sky_eagle',
    tier: 13,
    name: '하늘의 독수리',
    icon: '🦅',
    cost: 160,
    requires: ['legend_sword', 'iron_shield', 'thousand_bow'],
    minRequired: 2,
    effect: { type: 'critical_chance_bonus', value: 10 },
    description: '크리티컬 확률이 10% 증가합니다.'
  },
  {
    id: 'king_lion',
    tier: 13,
    name: '왕의 사자',
    icon: '🦁',
    cost: 160,
    requires: ['legend_sword', 'iron_shield', 'thousand_bow'],
    minRequired: 2,
    effect: { type: 'cps_percent', value: 50 },
    description: 'CPS가 50% 증가합니다.'
  },
  {
    id: 'earth_power',
    tier: 14,
    name: '대지의 기운',
    icon: '🌍',
    cost: 180,
    requires: ['fire_dragon', 'magic_unicorn', 'sky_eagle', 'king_lion'],
    minRequired: 2,
    effect: { type: 'cps_flat', value: 100 },
    description: '기본 CPS가 +100 증가합니다.'
  },
  {
    id: 'moon_gravity',
    tier: 14,
    name: '달의 인력',
    icon: '🌙',
    cost: 180,
    requires: ['fire_dragon', 'magic_unicorn', 'sky_eagle', 'king_lion'],
    minRequired: 2,
    effect: { type: 'interest', rate: 0.2 },
    description: '이자율이 +0.2% 증가합니다.'
  },
  {
    id: 'sun_energy',
    tier: 14,
    name: '태양 에너지',
    icon: '☀️',
    cost: 180,
    requires: ['fire_dragon', 'magic_unicorn', 'sky_eagle', 'king_lion'],
    minRequired: 2,
    effect: { type: 'all_bonus', value: 30 },
    description: '모든 효과가 30% 증가합니다.'
  },
  {
    id: 'infinite_universe',
    tier: 15,
    name: '무한 우주',
    icon: '🌌',
    cost: 200,
    requires: ['earth_power', 'moon_gravity', 'sun_energy'],
    minRequired: 2,
    effect: { type: 'all_bonus', value: 40 },
    description: '모든 효과가 40% 증가합니다.'
  },
  {
    id: 'blackhole',
    tier: 15,
    name: '블랙홀',
    icon: '🌀',
    cost: 200,
    requires: ['earth_power', 'moon_gravity', 'sun_energy'],
    minRequired: 2,
    effect: { type: 'cps_percent', value: 100 },
    description: 'CPS가 100% 증가합니다.'
  },
  {
    id: 'creation_nebula',
    tier: 15,
    name: '창조의 성운',
    icon: '💫',
    cost: 200,
    requires: ['earth_power', 'moon_gravity', 'sun_energy'],
    minRequired: 2,
    effect: { type: 'cps_percent', value: 80 },
    description: 'CPS가 80% 증가합니다.'
  },
  {
    id: 'supernova_explosion',
    tier: 15,
    name: '초신성 폭발',
    icon: '✨',
    cost: 200,
    requires: ['earth_power', 'moon_gravity', 'sun_energy'],
    minRequired: 2,
    effect: { type: 'click_percent', value: 100 },
    description: '클릭 데미지가 100% 증가합니다.'
  },
  {
    id: 'zeus_lightning',
    tier: 16,
    name: '제우스의 번개',
    icon: '⚡',
    cost: 250,
    requires: ['infinite_universe', 'blackhole', 'creation_nebula', 'supernova_explosion'],
    minRequired: 2,
    effect: { type: 'critical_chance_max', value: 100 },
    description: '모든 크리티컬 확률이 100%가 됩니다.'
  },
  {
    id: 'prometheus_fire',
    tier: 16,
    name: '프로메테우스의 불',
    icon: '🔥',
    cost: 250,
    requires: ['infinite_universe', 'blackhole', 'creation_nebula', 'supernova_explosion'],
    minRequired: 2,
    effect: { type: 'burning_max_bonus', value: 200 },
    description: '버닝 클릭의 최대 중첩 보너스가 200% 증가합니다.'
  },
  {
    id: 'chronos_ice',
    tier: 16,
    name: '크로노스의 얼음',
    icon: '❄️',
    cost: 250,
    requires: ['infinite_universe', 'blackhole', 'creation_nebula', 'supernova_explosion'],
    minRequired: 2,
    effect: { type: 'hourly_bonus', value: 100 },
    description: '매 시간마다 추가 100% 보너스를 받습니다.'
  },
  {
    id: 'omniscience',
    tier: 17,
    name: '전지',
    icon: '👁️',
    cost: 300,
    requires: ['zeus_lightning', 'prometheus_fire', 'chronos_ice'],
    minRequired: 2,
    effect: { type: 'all_chances_max', value: 100 },
    description: '게임 내 모든 확률 효과가 100% 발동합니다.'
  },
  {
    id: 'omnipotence',
    tier: 17,
    name: '전능',
    icon: '🧠',
    cost: 300,
    requires: ['zeus_lightning', 'prometheus_fire', 'chronos_ice'],
    minRequired: 2,
    effect: { type: 'all_bonus', value: 50 },
    description: '전체 효과가 50% 증가합니다.'
  },
  {
    id: 'omnipresence',
    tier: 17,
    name: '전력',
    icon: '💪',
    cost: 300,
    requires: ['zeus_lightning', 'prometheus_fire', 'chronos_ice'],
    minRequired: 2,
    effect: { type: 'click_percent', value: 200 },
    description: '클릭 데미지가 200% 증가합니다.'
  },
  {
    id: 'time_mastery',
    tier: 17,
    name: '신속',
    icon: '🏃',
    cost: 300,
    requires: ['zeus_lightning', 'prometheus_fire', 'chronos_ice'],
    minRequired: 2,
    effect: { type: 'cps_percent', value: 200 },
    description: 'CPS가 200% 증가합니다.'
  },
  {
    id: 'angel_blessing',
    tier: 18,
    name: '천사의 축복',
    icon: '👼',
    cost: 400,
    requires: ['omniscience', 'omnipotence', 'omnipresence', 'time_mastery'],
    minRequired: 2,
    effect: { type: 'all_bonus', value: 60 },
    description: '모든 효과가 60% 증가합니다.'
  },
  {
    id: 'devil_contract',
    tier: 18,
    name: '악마의 계약',
    icon: '😈',
    cost: 400,
    requires: ['omniscience', 'omnipotence', 'omnipresence', 'time_mastery'],
    minRequired: 2,
    effect: { type: 'star_gain_multiplier', value: 100 },
    description: '프레스티지 ⭐ 획득량이 100% 증가합니다.'
  },
  {
    id: 'grand_mage',
    tier: 18,
    name: '대마법사',
    icon: '🧙',
    cost: 400,
    requires: ['omniscience', 'omnipotence', 'omnipresence', 'time_mastery'],
    minRequired: 2,
    effect: { type: 'all_bonus', value: 50 },
    description: '모든 효과가 50% 증가합니다.'
  },
  {
    id: 'god_king',
    tier: 19,
    name: '신왕',
    icon: '👑',
    cost: 500,
    requires: ['angel_blessing', 'devil_contract', 'grand_mage'],
    minRequired: 2,
    effect: { type: 'all_bonus', value: 80 },
    description: '전체 효과가 80% 증가합니다.'
  },
  {
    id: 'god_queen',
    tier: 19,
    name: '신여왕',
    icon: '👸',
    cost: 500,
    requires: ['angel_blessing', 'devil_contract', 'grand_mage'],
    minRequired: 2,
    effect: { type: 'cps_percent', value: 150 },
    description: 'CPS가 150% 증가합니다.'
  },
  {
    id: 'god_prince',
    tier: 19,
    name: '신왕자',
    icon: '🤴',
    cost: 500,
    requires: ['angel_blessing', 'devil_contract', 'grand_mage'],
    minRequired: 2,
    effect: { type: 'click_percent', value: 150 },
    description: '클릭 데미지가 150% 증가합니다.'
  },
  {
    id: 'god_princess',
    tier: 19,
    name: '신공주',
    icon: '👸',
    cost: 500,
    requires: ['angel_blessing', 'devil_contract', 'grand_mage'],
    minRequired: 2,
    effect: { type: 'interest', rate: 1 },
    description: '이자율이 1% 증가합니다.'
  },
  {
    id: 'transcendent',
    tier: 20,
    name: '초월자',
    icon: '🏆',
    cost: 1000,
    requires: ['god_king', 'god_queen', 'god_prince', 'god_princess'],
    minRequired: 4,
    effect: { type: 'all_bonus', value: 100 },
    description: '모든 효과가 100% 증가합니다. 신을 초월한 존재가 되어 모든 한계를 극복합니다.'
  }
];

module.exports = { SKILLS };